### ISSUE TITLE
Date issue

### ISSUE THREAD

**Issue by ThomasVandermeersch** [ThomasVandermeersch/KorreKthor#10]
![image](https://user-images.githubusercontent.com/47421515/113206268-89736b80-926f-11eb-8601-dc70bb0247a8.png)

**Comment by Guigxs** [comment]
Done :+1:

**Comment by Guigxs** [comment]
Fix good date and hour format

**Comment by ThomasVandermeersch** [comment]
${("0" + date.getDate()).slice(-2)}/${("0" + (date.getMonth()+1)).slice(-2)}/${date.getFullYear()} - ${("0" + date.getHours()).slice(-2)}:${("0" + date.getMinutes()).slice(-2)}:${("0" + date.getSeconds()).slice(-2)}

---> do like this
