### ISSUE TITLE
Update answers detection method

### ISSUE THREAD

**Issue by Guigxs** [ThomasVandermeersch/KorreKthor#13]
- Change the way the answers are selected [here
](https://github.com/ThomasVandermeersch/KorreKthor/blob/main/Traitment_images/process_img.py#L160)

- Add logs for python executions

- Fix following bug
![image](https://user-images.githubusercontent.com/44777000/147860349-f797eb8c-51f6-4d91-83a4-d896942049f8.png)

**Comment by ThomasVandermeersch** [comment]
Resolved by Mr @KenN7
