### ISSUE TITLE
Upload copies

### ISSUE THREAD

**Issue by ThomasVandermeersch** [ThomasVandermeersch/KorreKthor#16]
A collaborator cannot upload copies

**Comment by KenN7** [comment]
is this fixed by af056a603033a80ce3f822d3fc8c56c7b4a1e22a ?

**Comment by ThomasVandermeersch** [comment]
> is this fixed by [af056a6](https://github.com/ThomasVandermeersch/KorreKthor/commit/af056a603033a80ce3f822d3fc8c56c7b4a1e22a) ?

Yes !
